apiVersion: skaffold/v1beta2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/gmaiztegi/todo-api-nest:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/gmaiztegi/todo-api-nest:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: todo-api-nest
        chartPath: charts/todo-api-nest
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/gmaiztegi/todo-api-nest"
          image.tag: "{{.DIGEST_HEX}}"
